### ISSUE TITLE
./mailgun.go:39:33: too many arguments in call to mailgun.NewMailgun

### ISSUE THREAD

**Issue by evityuk** [TykTechnologies/tyk-email-driver#11]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
Running 
```
go get -v ./...
```
fails with error:
./mailgun.go:39:33: too many arguments in call to mailgun.NewMailgun
due to NewMailgun func signature changes
https://github.com/mailgun/mailgun-go/commit/c1b5c374931068e385f1f5e32f2498d09dd6c032#diff-04c6e90faac2675aa89e2176d2eec7d8R51

What is the expected behavior?
```
go get -v ./...
```
should finish without error and install all dependencies 

Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?
2.8

Should it be updated

**Comment by adelowo** [comment]
Is there a reason why the mailgun library isn't vendored in the first place, like others in https://github.com/TykTechnologies/tyk-email-driver/blob/master/vendor/vendor.json ?

**Comment by adelowo** [comment]
So I have implemented the required changes at https://github.com/adelowo/tyk-email-driver/commit/fa01f35d0b6f8da45dffe772cbd2ddeecb24db1b but the newer version of the mailgun library uses ___versioned import paths___  so it only supports modules. So you have to be at `>=1.11`. 

Even if you are `1.11` and disable modules with `export GO111MODULE=off`, it still wouldn't work.

`govendor fetch` didn't solve this as there is actually no package like `mailgun-go/v3`
