### ISSUE TITLE
Add SMTP Email Driver

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk-email-driver#4]
Hi,
it would be interesting to have a smtp email backend driver for tyk dashboard for on-premise installation. We have no way to send email from tyk with our internal smtp.
I will pull a request for this feature.

Thanks

**Comment by buger** [comment]
Will be great if someone do a PR for this :)

**Comment by joshblakeley** [comment]
@buger https://github.com/TykTechnologies/tyk-email-driver/pull/5
